### ISSUE TITLE
A small query about label leakage

### ISSUE THREAD

**Issue by manojj2891** [Featuretools/NYC-Taxi-Demo#2]
Hi,

Thanks for the detailed code.

But have a doubt about label leakage here. While calculating features we are also including "trip_duration". Also saw a couple of features being created using the feature. Shouldn't we remove the variable before calculating features?

Thanks,
Manoj

**Comment by kmax12** [comment]
@manojj2891 We'd be happy to answer. Can you post this question on StackOverflow with the featuretools tag? https://stackoverflow.com/questions/tagged/featuretools.
